services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_DATABASE=produtos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mysql-net
networks:
  mysql-net:
    name: mysql-net
    driver: bridge